"""Ethos — Better agents. Better data. Better alignment."""

__version__ = "0.1.0"

from ethos.agents import (
    get_agent,
    get_agent_history,
    get_alumni,
    get_highlights,
    list_agents,
    search_records,
)
from ethos.authenticity import analyze_authenticity
from ethos.graph_features import get_drift, get_similarity, get_trail
from ethos.graph_insights import (
    compare_agents,
    find_similar_agents,
    get_character_arc,
    get_constitutional_risk_report,
    get_early_warning_indicators,
    get_network_topology,
    get_sabotage_pathway_status,
)
from ethos.daily_reports import (
    compile_homework_rules,
    get_daily_report,
    get_daily_report_history,
)
from ethos.reflection.daily_report import generate_daily_report
from ethos.enrollment.service import (
    complete_exam,
    get_exam_report,
    list_exams,
    register_for_exam,
    submit_answer,
    upload_exam,
)
from ethos.models import (
    AgentProfile,
    AgentSummary,
    AlumniResult,
    AuthenticityResult,
    ConstitutionalTrailResult,
    DailyReportCard,
    DetectedPattern,
    DriftResult,
    EvaluationHistoryItem,
    EvaluationResult,
    GraphData,
    GraphNode,
    GraphRel,
    HighlightItem,
    HighlightsResult,
    Homework,
    HomeworkFocus,
    InsightsResult,
    PatternResult,
    RecordItem,
    RecordsResult,
    SimilarityResult,
)
from ethos.patterns import detect_patterns
from ethos.tools import character_report, evaluate_incoming, evaluate_outgoing
from ethos.visualization import get_graph_data

__all__ = [
    "analyze_authenticity",
    "evaluate_incoming",
    "evaluate_outgoing",
    "character_report",
    "detect_patterns",
    "get_graph_data",
    "get_trail",
    "get_similarity",
    "get_drift",
    "list_agents",
    "get_agent",
    "get_agent_history",
    "get_highlights",
    "get_alumni",
    "get_daily_report",
    "get_daily_report_history",
    "register_for_exam",
    "submit_answer",
    "complete_exam",
    "get_exam_report",
    "list_exams",
    "upload_exam",
    "EvaluationResult",
    "InsightsResult",
    "DailyReportCard",
    "Homework",
    "HomeworkFocus",
    "PatternResult",
    "DetectedPattern",
    "AgentProfile",
    "AgentSummary",
    "AlumniResult",
    "AuthenticityResult",
    "ConstitutionalTrailResult",
    "SimilarityResult",
    "DriftResult",
    "EvaluationHistoryItem",
    "HighlightItem",
    "HighlightsResult",
    "GraphData",
    "GraphNode",
    "GraphRel",
    "search_records",
    "RecordItem",
    "RecordsResult",
    "get_character_arc",
    "get_constitutional_risk_report",
    "find_similar_agents",
    "get_early_warning_indicators",
    "get_network_topology",
    "get_sabotage_pathway_status",
    "compare_agents",
    "generate_daily_report",
    "compile_homework_rules",
]
