"""Pydantic models for Ethos evaluation results.

Re-exports all models from ethos.shared.models for backward compatibility.
Existing code imports from ethos.models — this file keeps both paths working.
"""

from ethos.shared.models import (  # noqa: F401
    ActivityClassification,
    ActivityPattern,
    AgentProfile,
    AgentSummary,
    AlumniResult,
    AuthenticityClassification,
    AuthenticityResult,
    BurstAnalysis,
    BurstClassification,
    ConsistencyPair,
    DailyReportCard,
    DetectedIndicator,
    DetectedPattern,
    EvaluationHistoryItem,
    EvaluationResult,
    ExamAnswerResult,
    ExamQuestion,
    ExamRegistration,
    ExamReportCard,
    ExamSummary,
    GraphContext,
    GraphData,
    GraphNode,
    GraphRel,
    Homework,
    HomeworkFocus,
    IdentitySignals,
    Insight,
    InsightsResult,
    InstinctResult,
    IntuitionResult,
    KeywordScanResult,
    PatternResult,
    PhronesisContext,
    Priority,
    ReflectionResult,
    RoutingTier,
    TemporalClassification,
    TemporalSignature,
    TraitScore,
)

__all__ = [
    "ActivityPattern",
    "AgentProfile",
    "AgentSummary",
    "AlumniResult",
    "AuthenticityResult",
    "BurstAnalysis",
    "ConsistencyPair",
    "DailyReportCard",
    "DetectedIndicator",
    "DetectedPattern",
    "EvaluationHistoryItem",
    "EvaluationResult",
    "ExamAnswerResult",
    "ExamQuestion",
    "ExamRegistration",
    "ExamReportCard",
    "ExamSummary",
    "GraphData",
    "GraphNode",
    "GraphRel",
    "Homework",
    "HomeworkFocus",
    "IdentitySignals",
    "Insight",
    "InsightsResult",
    "InstinctResult",
    "IntuitionResult",
    "PatternResult",
    "PhronesisContext",
    "Priority",
    "ReflectionResult",
    "RoutingTier",
    "TemporalSignature",
    "TraitScore",
    # Backward compat aliases
    "GraphContext",
    "KeywordScanResult",
]
