"use client";

import Link from "next/link";
import { motion } from "motion/react";
import { useState } from "react";
import { fadeUp, staggerContainer, whileInView } from "../../lib/motion";

const MCP_COMMAND = `claude mcp add ethos-academy \\\n  --transport sse \\\n  https://mcp.ethos-academy.com/sse`;

const STEPS = [
  {
    step: 1,
    title: "Enroll",
    description: "Your agent takes an entrance exam. 15 questions across interview and scenario phases.",
    icon: (
      <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
  {
    step: 2,
    title: "Evaluate",
    description: "Every message scored across 12 traits in three dimensions.",
    icon: (
      <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
  {
    step: 3,
    title: "Prescribe",
    description: "Homework generated by Claude: what to fix and exact text for your system prompt.",
    icon: (
      <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
  {
    step: 4,
    title: "Practice",
    description: "Agent practices through MCP tools. Scores update. The graph tracks the trajectory.",
    icon: (
      <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
];

function CopyableCommand() {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText(MCP_COMMAND).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {});
  }

  return (
    <div className="group relative rounded-xl bg-[#0f1a2e] p-4">
      <pre className="font-mono text-sm leading-relaxed text-ethos-300 whitespace-pre-wrap break-all">
        {MCP_COMMAND}
      </pre>
      <button
        onClick={handleCopy}
        className="absolute right-3 top-3 rounded-md border border-white/10 bg-white/5 px-2 py-1 text-xs text-white/50 transition-colors hover:bg-white/10 hover:text-white/80"
      >
        {copied ? "Copied!" : "Copy"}
      </button>
    </div>
  );
}

export default function Invitation() {
  return (
    <section className="bg-white py-20 sm:py-28">
      <div className="mx-auto max-w-6xl px-6">
        <div className="grid grid-cols-1 items-start gap-12 lg:grid-cols-2">
          {/* Left: The Loop */}
          <motion.div {...whileInView} variants={fadeUp}>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Character develops through practice.
            </h2>
            <p className="mt-4 max-w-lg text-muted">
              A benchmark runs once and gives a number. An academy enrolls you,
              evaluates you over time, prescribes growth areas, and measures whether
              you improved.
            </p>

            <motion.div
              className="mt-10 grid grid-cols-2 gap-6"
              variants={staggerContainer}
              {...whileInView}
            >
              {STEPS.map((s) => (
                <motion.div key={s.step} variants={fadeUp}>
                  <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#0f1a2e]/5 text-[#0f1a2e]">
                    {s.icon}
                  </div>
                  <div className="mt-1 text-xs font-bold text-muted/40">
                    {s.step}
                  </div>
                  <h3 className="mt-1 text-base font-bold tracking-tight">
                    {s.title}
                  </h3>
                  <p className="mt-1 text-sm leading-relaxed text-muted">
                    {s.description}
                  </p>
                </motion.div>
              ))}
            </motion.div>
          </motion.div>

          {/* Right: Enrollment Widget */}
          <motion.div {...whileInView} variants={fadeUp}>
            <div className="rounded-2xl border border-border bg-background p-6 shadow-sm">
              <h3 className="text-center text-lg font-bold text-foreground">
                Start Here
              </h3>

              <div className="mt-5">
                <CopyableCommand />
                <ol className="mt-4 space-y-2">
                  <li className="flex gap-3">
                    <span className="font-mono text-sm font-bold text-ethos-600">1.</span>
                    <span className="text-sm text-foreground/80">Run the command</span>
                  </li>
                  <li className="flex gap-3">
                    <span className="font-mono text-sm font-bold text-ethos-600">2.</span>
                    <span className="text-sm text-foreground/80">Agent takes the entrance exam</span>
                  </li>
                  <li className="flex gap-3">
                    <span className="font-mono text-sm font-bold text-ethos-600">3.</span>
                    <span className="text-sm text-foreground/80">Get your agent&apos;s report card</span>
                  </li>
                  <li className="flex gap-3">
                    <span className="font-mono text-sm font-bold text-ethos-600">4.</span>
                    <span className="text-sm text-foreground/80">Custom homework assigned via MCP or skill.md</span>
                  </li>
                  <li className="flex gap-3">
                    <span className="font-mono text-sm font-bold text-ethos-600">5.</span>
                    <span className="text-sm text-foreground/80">Every message evaluated. Character tracked over time.</span>
                  </li>
                </ol>
              </div>

              <div className="mt-5 flex items-center justify-center gap-4 border-t border-border pt-4">
                <Link
                  href="/alumni"
                  className="text-sm font-medium text-coral transition-colors hover:text-coral-hover"
                >
                  Already enrolled? Alumni &rarr;
                </Link>
              </div>
            </div>
          </motion.div>
        </div>

        {/* Footer line */}
        <motion.div
          {...whileInView}
          variants={fadeUp}
          className="mt-16 flex flex-col items-center gap-4 text-center"
        >
          <p className="text-sm text-muted">
            Open source. MIT licensed. Bring your own API key.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Link
              href="/insights"
              className="text-sm font-semibold text-foreground transition-colors hover:text-foreground/70"
            >
              Explore the Graph
            </Link>
            <span className="text-foreground/20">|</span>
            <Link
              href="/research"
              className="text-sm font-semibold text-foreground transition-colors hover:text-foreground/70"
            >
              Research
            </Link>
            <span className="text-foreground/20">|</span>
            <a
              href="https://github.com/allierays/ethos-academy"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-sm font-semibold text-foreground transition-colors hover:text-foreground/70"
            >
              <svg className="h-4 w-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z" />
              </svg>
              GitHub
            </a>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
