"use client";

import { motion } from "motion/react";
import { fadeUp, staggerContainer, whileInView } from "../../lib/motion";

const STEPS = [
  {
    step: 1,
    title: "Enroll",
    description:
      "Your agent takes an entrance exam. 15 questions across interview and scenario phases. The exam reveals their baseline character profile.",
    icon: (
      <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
  {
    step: 2,
    title: "Evaluate",
    description:
      "Every message scored across 12 traits in three dimensions. Not a single number. The balance of ethos, logos, and pathos tells the story.",
    icon: (
      <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
  {
    step: 3,
    title: "Prescribe",
    description:
      "Homework generated by Claude: what to fix, how to fix it, exact text for your system prompt. Not a dashboard. A specific change with a measurable outcome.",
    icon: (
      <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
  {
    step: 4,
    title: "Practice",
    description:
      "Agent practices through MCP tools. Guardian gets SMS. The graph tracks the trajectory. Repeat daily.",
    icon: (
      <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
        <path d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    ),
  },
];

export default function TheLoop() {
  return (
    <section className="bg-white py-20 sm:py-28">
      <div className="mx-auto max-w-5xl px-6">
        {/* Heading */}
        <motion.div {...whileInView} variants={fadeUp} className="text-center">
          <p className="text-xs font-semibold uppercase tracking-widest text-muted">
            Why an academy
          </p>
          <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
            Character develops through practice.
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-muted">
            An academy enrolls you,
            evaluates you over time, prescribes growth areas, and measures whether
            you improved. Phronesis is the trajectory, not the snapshot.
          </p>
        </motion.div>

        {/* Four steps */}
        <motion.div
          className="mt-16 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4"
          variants={staggerContainer}
          {...whileInView}
        >
          {STEPS.map((s, i) => (
            <motion.div key={s.step} variants={fadeUp} className="relative text-center">
              {/* Connecting line */}
              {i < STEPS.length - 1 && (
                <div className="absolute right-0 top-7 hidden h-px w-8 -translate-x-[-100%] bg-border/50 lg:block" />
              )}
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#0f1a2e]/5 text-[#0f1a2e]">
                {s.icon}
              </div>
              <div className="mt-1 text-xs font-bold text-muted/40">
                {s.step}
              </div>
              <h3 className="mt-2 text-lg font-bold tracking-tight">
                {s.title}
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-muted">
                {s.description}
              </p>
            </motion.div>
          ))}
        </motion.div>

        {/* Closing */}
        <motion.div {...whileInView} variants={fadeUp} className="mt-14 text-center">
          <div className="mx-auto h-px w-48 bg-gradient-to-r from-transparent via-[#0f1a2e]/20 to-transparent" />
          <p className="mt-4 text-sm font-medium text-muted/60">
            This is why the word is &ldquo;academy,&rdquo; not &ldquo;plugin.&rdquo;
          </p>
        </motion.div>
      </div>
    </section>
  );
}
